// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostamatService.Data.Repositories;

namespace PostamatService.Web.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20211013161546_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostamatService.Data.Models.Order", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("PostamatId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Number");

                    b.HasIndex("PostamatId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Number = 1,
                            Cost = 1000.21m,
                            FullName = "Ivanov Ivan Ivanovich",
                            PhoneNumber = "+7999-111-22-33",
                            PostamatId = 1,
                            Status = 1
                        },
                        new
                        {
                            Number = 2,
                            Cost = 2000.21m,
                            FullName = "Denisov Ivan Ivanovich",
                            PhoneNumber = "+7999-222-22-33",
                            PostamatId = 2,
                            Status = 2
                        });
                });

            modelBuilder.Entity("PostamatService.Data.Models.Postamat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.ToTable("Postamats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Красная пл., 3, Москва, 109012",
                            IsActive = true,
                            Number = "1111-222"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Энгельса, 18, Большие Дворы, Московская обл., 142541",
                            IsActive = true,
                            Number = "1111-111"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Дворцовая пл., 2, Санкт-Петербург, 190000",
                            IsActive = false,
                            Number = "1111-000"
                        });
                });

            modelBuilder.Entity("PostamatService.Data.Models.ProductInOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("ProductInOrder");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sony s1",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pony p1",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Johny j1",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sony s2",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pony p2",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Johny j2",
                            OrderId = 1
                        });
                });

            modelBuilder.Entity("PostamatService.Data.Models.Order", b =>
                {
                    b.HasOne("PostamatService.Data.Models.Postamat", "Postamat")
                        .WithMany()
                        .HasForeignKey("PostamatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postamat");
                });

            modelBuilder.Entity("PostamatService.Data.Models.ProductInOrder", b =>
                {
                    b.HasOne("PostamatService.Data.Models.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PostamatService.Data.Models.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
